Repository skorch-dev/skorch, pull requests merged in 2018-05, with the labels that each got.

#192 Change forward/forward_iter's location to device
  skorch/net.py
  skorch/tests/test_net.py
Labels: enhancement, r0.2.0

#193 Resolve #187 by passing named params as list
  skorch/net.py
Labels: bug, r0.2.0

#194 Resolve #183 by syncing LR schedulers
  skorch/callbacks/lr_scheduler.py
Labels: r0.2.0

#196 Update install instruction for pytorch 0.4 in README.
  README.rst
Labels: r0.2.0

#188 fix problem with callback params
  docs/user/callbacks.rst
  skorch/callbacks/base.py
  skorch/net.py
  skorch/tests/test_callbacks.py
  skorch/tests/test_net.py
Labels: bug, enhancement, r0.2.0

#179 Non-functional cleanups and pylint satisfaction.
  skorch/callbacks/__init__.py
  skorch/callbacks/logging.py
  skorch/callbacks/lr_scheduler.py
  skorch/callbacks/scoring.py
  skorch/net.py
  skorch/tests/test_dataset.py
  skorch/tests/test_lr_scheduler.py
  skorch/tests/test_net.py
  skorch/tests/test_utils.py
  skorch/utils.py
Labels: r0.2.0

#198 Classifier only applies log if nll loss
  docs/user/neuralnet.rst
  skorch/net.py
  skorch/tests/test_net.py
Labels: r0.2.0

#199 Fix bug where property _default_callbacks on NeuralNet was missing.
  skorch/net.py
Labels: r0.2.0

#221 Add an answer to FAQ that explains how to use sample_weight.
  docs/user/FAQ.rst
Labels: enhancement

#219 Bugfix/no grad during valid
  skorch/net.py
  skorch/tests/test_net.py
Labels: bug

#227 ENH: batch_size=-1 uses whole dataset
  skorch/net.py
  skorch/tests/test_net.py
Labels: enhancement, r0.3.0

#206 Fix a bug with caching that sometimes prevented infer to be reset.
  skorch/callbacks/scoring.py
  skorch/tests/callbacks/test_scoring.py
Labels: bug, r0.3.0

#209 lr scheduler can now monitor other fields
  skorch/callbacks/lr_scheduler.py
  skorch/callbacks/training.py
  skorch/tests/test_lr_scheduler.py
Labels: enhancement, r0.3.0
