Repository skorch-dev/skorch, pull requests merged in 2019-05, with the labels that each got.

#463 [MRG] ENH Uses checkpoint internally
  CHANGES.md
  skorch/callbacks/training.py
  skorch/tests/callbacks/test_training.py
Labels: bug

#454 Increase notebook version to >=5.7.8 in nuclei example
  examples/nuclei_image_segmentation/requirements.txt
Labels: security

#476 Remove deprecations for 0.6.0 release
  .travis.yml
  CHANGES.md
  README.rst
  skorch/callbacks/training.py
  skorch/dataset.py
  skorch/helper.py
  skorch/history.py
  skorch/net.py
  skorch/tests/callbacks/test_training.py
  skorch/tests/test_helper.py
  skorch/tests/test_history.py
  skorch/tests/test_net.py
Labels: r0.6.0

#480 Minor improvements to MNIST example
  notebooks/MNIST.ipynb
Labels: enhancement
